"""expand page_visit with device info

Revision ID: 3d2fe6c56acc
Revises: 71ac0fac8f5c
Create Date: 2026-06-25 22:08:22.770598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2fe6c56acc'
down_revision: Union[str, None] = '71ac0fac8f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_visits', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('page_visits', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('page_visits', sa.Column('browser', sa.String(length=100), nullable=True))
    op.add_column('page_visits', sa.Column('browser_version', sa.String(length=50), nullable=True))
    op.add_column('page_visits', sa.Column('os', sa.String(length=100), nullable=True))
    op.add_column('page_visits', sa.Column('os_version', sa.String(length=50), nullable=True))
    op.add_column('page_visits', sa.Column('device_type', sa.String(length=50), nullable=True))
    op.add_column('page_visits', sa.Column('accept_language', sa.String(length=255), nullable=True))
    op.add_column('page_visits', sa.Column('referer', sa.Text(), nullable=True))
    op.add_column('page_visits', sa.Column('screen_width', sa.Integer(), nullable=True))
    op.add_column('page_visits', sa.Column('screen_height', sa.Integer(), nullable=True))
    op.add_column('page_visits', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('page_visits', sa.Column('language', sa.String(length=20), nullable=True))
    op.add_column('page_visits', sa.Column('platform', sa.String(length=100), nullable=True))
    op.add_column('page_visits', sa.Column('page_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_visits', 'page_url')
    op.drop_column('page_visits', 'platform')
    op.drop_column('page_visits', 'language')
    op.drop_column('page_visits', 'timezone')
    op.drop_column('page_visits', 'screen_height')
    op.drop_column('page_visits', 'screen_width')
    op.drop_column('page_visits', 'referer')
    op.drop_column('page_visits', 'accept_language')
    op.drop_column('page_visits', 'device_type')
    op.drop_column('page_visits', 'os_version')
    op.drop_column('page_visits', 'os')
    op.drop_column('page_visits', 'browser_version')
    op.drop_column('page_visits', 'browser')
    op.drop_column('page_visits', 'user_agent')
    op.drop_column('page_visits', 'ip_address')
    # ### end Alembic commands ###
