"""add page_visit table

Revision ID: 631058442479
Revises: 4077311c523b
Create Date: 2026-06-25 21:07:43.102755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631058442479'
down_revision: Union[str, None] = '4077311c523b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_visits',
    sa.Column('anonymous_client_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_visits_anonymous_client_id'), 'page_visits', ['anonymous_client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_visits_anonymous_client_id'), table_name='page_visits')
    op.drop_table('page_visits')
    # ### end Alembic commands ###
