"""Add course_code

Revision ID: 8fc2ad7dc8cc
Revises: 0001_initial
Create Date: 2026-06-25 16:43:50.105688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc2ad7dc8cc'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('philosophies', sa.Column('course_code', sa.String(length=32), server_default='MLN111', nullable=False))
    op.create_index(op.f('ix_philosophies_course_code'), 'philosophies', ['course_code'], unique=False)
    op.add_column('questions', sa.Column('course_code', sa.String(length=32), server_default='MLN111', nullable=False))
    op.create_index(op.f('ix_questions_course_code'), 'questions', ['course_code'], unique=False)
    op.add_column('survey_sessions', sa.Column('course_code', sa.String(length=32), server_default='MLN111', nullable=False))
    op.create_index(op.f('ix_survey_sessions_course_code'), 'survey_sessions', ['course_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_sessions_course_code'), table_name='survey_sessions')
    op.drop_column('survey_sessions', 'course_code')
    op.drop_index(op.f('ix_questions_course_code'), table_name='questions')
    op.drop_column('questions', 'course_code')
    op.drop_index(op.f('ix_philosophies_course_code'), table_name='philosophies')
    op.drop_column('philosophies', 'course_code')
    # ### end Alembic commands ###
