QUESTIONS = [
    {
        "code": "q001",
        "section": "work_discipline",
        "text": "Khi mọi thứ rối tung, mình thường hỏi: “Phần nào mình còn kiểm soát được?”",
        "order_index": 1,
        "illustration_key": "deadline_monster",
        "weights": {"stoicism": 2, "pragmatism": 1},
    },
    {
        "code": "q002",
        "section": "meaning_life",
        "text": "Mình thấy cuộc sống không cần có ý nghĩa sẵn; tự mình tạo ra ý nghĩa cũng ổn.",
        "order_index": 2,
        "illustration_key": "meaning_void",
        "weights": {"existentialism": 2, "absurdism": 1},
    },
    {
        "code": "q003",
        "section": "ethics_society",
        "text": "Nếu một hành động giúp nhiều người tốt hơn, mình có thể chấp nhận vài bất tiện cá nhân.",
        "order_index": 3,
        "illustration_key": "society_pyramid",
        "weights": {"utilitarianism": 2, "confucian_ethics": 1},
    },
    {
        "code": "q004",
        "section": "emotions_conflict",
        "text": "Một cuộc sống bình yên, ít drama, có bạn bè tốt nghe rất đáng mơ ước.",
        "order_index": 4,
        "illustration_key": "chill_cloud",
        "weights": {"epicureanism": 2, "humanism": 1},
    },
    {
        "code": "q005",
        "section": "meaning_life",
        "text": "Mình thường nghi ngờ những câu kiểu “ai cũng phải sống như thế này”.",
        "order_index": 5,
        "illustration_key": "meaning_void",
        "weights": {"nihilism": 2, "existentialism": 1},
    },
    {
        "code": "q006",
        "section": "emotions_conflict",
        "text": "Khi đời vô lý như một bug không có stack trace, mình vẫn cố sống vui.",
        "order_index": 6,
        "illustration_key": "meaning_void",
        "weights": {"absurdism": 2, "existentialism": 1},
    },
    {
        "code": "q007",
        "section": "ethics_society",
        "text": "Mình tin con người có thể tốt hơn nếu được giáo dục và đối xử tử tế.",
        "order_index": 7,
        "illustration_key": "cartoon_philosopher",
        "weights": {"humanism": 2, "confucian_ethics": 1},
    },
    {
        "code": "q008",
        "section": "ethics_society",
        "text": "Quy tắc và trách nhiệm giúp xã hội đỡ biến thành một group chat hỗn loạn.",
        "order_index": 8,
        "illustration_key": "society_pyramid",
        "weights": {"confucian_ethics": 2, "utilitarianism": 1},
    },
    {
        "code": "q009",
        "section": "meaning_life",
        "text": "Mình tin ý tưởng, niềm tin và giá trị bên trong có thể định hình cách con người sống.",
        "order_index": 9,
        "illustration_key": "cartoon_philosopher",
        "weights": {"idealism": 2, "existentialism": 1},
    },
    {
        "code": "q010",
        "section": "work_discipline",
        "text": "Muốn hiểu một vấn đề, trước hết cần nhìn vào điều kiện thực tế, dữ kiện và hoàn cảnh cụ thể.",
        "order_index": 10,
        "illustration_key": "deadline_monster",
        "weights": {"materialism": 2, "pragmatism": 1},
    },
    {
        "code": "q011",
        "section": "work_discipline",
        "text": "Khi làm việc nhóm, mình ưu tiên cách nào chạy được trước, hoàn hảo tính sau.",
        "order_index": 11,
        "illustration_key": "deadline_monster",
        "weights": {"pragmatism": 2},
    },
    {
        "code": "q012",
        "section": "work_discipline",
        "text": "Mình dễ tự ép bản thân phải mạnh mẽ, kể cả khi thật ra mình hơi mệt.",
        "order_index": 12,
        "illustration_key": "cartoon_philosopher",
        "weights": {"stoicism": 2},
    },
    {
        "code": "q013",
        "section": "meaning_life",
        "text": "Mình quan tâm việc lựa chọn của mình có đúng với con người thật của mình không.",
        "order_index": 13,
        "illustration_key": "meaning_void",
        "weights": {"existentialism": 2},
    },
    {
        "code": "q014",
        "section": "ethics_society",
        "text": "Nếu phải chọn, mình ưu tiên giải pháp có lợi cho tập thể hơn là chỉ có lợi cho riêng mình.",
        "order_index": 14,
        "illustration_key": "society_pyramid",
        "weights": {"utilitarianism": 2, "confucian_ethics": 1},
    },
    {
        "code": "q015",
        "section": "emotions_conflict",
        "text": "Mình không thích chạy theo thành công nếu cái giá là mất hết sự bình yên.",
        "order_index": 15,
        "illustration_key": "chill_cloud",
        "weights": {"epicureanism": 2},
    },
    {
        "code": "q016",
        "section": "meaning_life",
        "text": "Đôi khi mình thấy nhiều thứ xã hội coi là “quan trọng” thật ra khá vô nghĩa.",
        "order_index": 16,
        "illustration_key": "meaning_void",
        "weights": {"nihilism": 2, "absurdism": 1},
    },
    {
        "code": "q017",
        "section": "emotions_conflict",
        "text": "Khi gặp chuyện khó chịu, mình hay biến nó thành trò đùa để dễ sống tiếp.",
        "order_index": 17,
        "illustration_key": "meaning_void",
        "weights": {"absurdism": 2},
    },
    {
        "code": "q018",
        "section": "emotions_conflict",
        "text": "Mình thường nhìn người khác với niềm tin rằng ai cũng có khả năng phát triển.",
        "order_index": 18,
        "illustration_key": "cartoon_philosopher",
        "weights": {"humanism": 2},
    },
    {
        "code": "q019",
        "section": "ethics_society",
        "text": "Mình nghĩ mỗi người nên làm tốt vai trò của mình để tập thể vận hành ổn.",
        "order_index": 19,
        "illustration_key": "society_pyramid",
        "weights": {"confucian_ethics": 2},
    },
    {
        "code": "q020",
        "section": "work_discipline",
        "text": "Mình thích những kết luận có bằng chứng, dữ liệu hoặc kết quả cụ thể hơn là nói chung chung.",
        "order_index": 20,
        "illustration_key": "deadline_monster",
        "weights": {"materialism": 2, "pragmatism": 1},
    },
]
